import { type } from 'os'
import React from 'react'
import AnimeList from '../components/animes/AnimeList'
import {List} from '../models/Types'
import { MongoClient } from 'mongodb'




// const DUMMY_LIST = [
//   {
//     id: 'a1',
//     title: 'Attack on Titans',
//     image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallpapercave.com%2Fwp%2Fwp1837557.jpg&f=1&nofb=1',
//     genre: 'action',
//   },
//   {
//     id: 'a2',
//     title: 'Demon Slayer',
//     image: 'https://media.nichegamer.com/wp-content/uploads/2021/06/24114131/Demon-Slayer-Kimetsu-no-Yaiba-The-Hinokami-Chronicles-06-24-21-1-768x432.jpg',
//     genre: 'action',
//   },
//   {
//     id: 'a3',
//     title: 'Another',
//     image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallup.net%2Fwp-content%2Fuploads%2F2019%2F09%2F707160-anime-series-characters-misaki-mei-sakakibara-kouichi-another-1.jpg&f=1&nofb=1',
//     genre: 'horror',
//   },
//   {
//     id: 'a4',
//     title: 'SAMURAI CHAMPLOO',
//     image: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2F736x%2Fd1%2Fa5%2F30%2Fd1a530522bd877eac9e1fa05b43e1e8e--art-school-samurai.jpg&f=1&nofb=1',
//     genre: 'Adventure, Comedy, Samurai'
//   }
// ]

const HomePage:React.FC<{animes: List}> = (props) => {
  return (
  
      <AnimeList animes={props.animes}/>

  )
}

export default HomePage


const MONGO_URI_1:any = process.env.MONGO_URI_1

export async function getStaticProps(){
  // fetch data from an API
  const client = await MongoClient.connect(MONGO_URI_1);
  const db = client.db()
  const animeCollection = db.collection('animes')

  const animes = await animeCollection.find().toArray()

  client.close()

  return{
    props: {
      animes: animes.map(anime => ({
        id: anime._id.toString(),
        title: anime.title,
        image: anime.image,
        genre: anime.genre
      }))
    },
    //pre-generated on the server every 10 seconds
     revalidate: 10,
  }

} 

// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home
